sudo: required

services:
  - docker

script:
  - docker-compose build
  - echo "$DOCKER_PASSWORD | docker login -u "$DOCKER_USER" --password-stdin
  - docker tag fuzzymatch-server $DOCKER_USER/fuzzymatch-server
  - docker tag fuzzymatch-client $DOCKER_USER/fuzzymatch-client
  - docker push $DOCKER_USER/fuzzymatch-server
  - docker push $DOCKER_USER/fuzzymatch-client

notifications:
  slack: fuzzy-matching:kyPay6TFOQrTMffKJRy6FoAZ
