sudo: required

services:
  - docker

jobs:
  include:
    - stage: build
      script:
        - docker-compose build
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
        - docker tag fuzzy $DOCKER_USER/fuzzy
        - docker push $DOCKER_USER/fuzzy

notifications:
  slack: fuzzy-matching:kyPay6TFOQrTMffKJRy6FoAZ
