sudo: required

services:
  - docker

jobs:
  include:
    - stage: build
      script:
        - docker-compose build
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
        - docker tag fuzzy-api $DOCKER_USER/fuzzy-api
        - docker push $DOCKER_USER/fuzzy-api
        - docker tag fuzzy-worker $DOCKER_USER/fuzzy-worker
        - docker push $DOCKER_USER/fuzzy-worker

notifications:
  slack: fuzzy-matching:kyPay6TFOQrTMffKJRy6FoAZ
