sudo: required

services:
  - docker

jobs:
  include:
    - stage: build
      script: docker-compose build
    - deploy:
      script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
      script: docker tag fuzzymatch-server $DOCKER_USER/fuzzymatch-server
      script: docker tag fuzzymatch-client $DOCKER_USER/fuzzymatch-client
      script: docker push $DOCKER_USER/fuzzymatch-server
      script: docker push $DOCKER_USER/fuzzymatch-client

notifications:
  slack: fuzzy-matching:kyPay6TFOQrTMffKJRy6FoAZ
