version: "3"
services:
  app:
    image: fuzzy
    build:
      context: ./
    ports:
      - "80:80"
    volumes:
      - fuzzy-db:/data
    environment:
      - DB_PATH=/data/data.db

volumes:
  fuzzy-db: {}
