version: '3'
services:
  api:
    image: fuzzymatch-server
    build: 
      context: ./server
    ports:
      - "5000:80"

  client:
    image: fuzzymatch-client
    build:
      context: ./client
    ports:
      - "80:8080"
